service: nanny

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-api-cloudfront

custom:
  defaultStage: development
  defaultRegion: eu-north-1
  apigwBinary:
    types:
      - 'image/*'
  apiCloudFront:
    domain: images.sjofartstidningen.se
    certificate: ${env:AWS_CERTIFICATE_ARN}
    compress: true
    cookies: none
    headers:
      - Accept
    querystring: all

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: ${env:S3_BUCKET_ARN}

package:
  exclude:
    - node_modules/**

functions:
  processImage:
    environment:
      NODE_ENV: ${self:provider.stage}
      S3_BUCKET: ${env:S3_BUCKET_NAME}
    handler: dist/index.processImage
    description: Image processing service
    events:
      - http:
          path: '{proxy+}'
          method: get
          contentHandling: CONVERT_TO_BINARY
