service: nanny
frameworkVersion: '2'

plugins:
  - serverless-api-cloudfront

custom:
  defaultStage: staging
  defaultRegion: 'eu-north-1'
  apiCloudFront:
    domain: ${env:DOMAIN}
    certificate: ${env:AWS_CERTIFICATE_ARN}
    compress: true
    cookies: 'none'
    headers:
      - 'Accept'
    querystring: 'all'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: ${env:S3_BUCKET_ARN}

  apiGateway:
    binaryMediaTypes:
      - '*/*'
      - 'image/*'
      - 'image/apng'
      - 'image/gif'
      - 'image/jpeg'
      - 'image/png'
      - 'image/svg+xml'
      - 'image/webp'

package:
  exclude:
    - '**/*'
  include:
    - dist/**

functions:
  processImage:
    environment:
      NODE_ENV: ${self:provider.stage}
      S3_BUCKET: ${env:S3_BUCKET_NAME}
      FORCE_WEBP: true
    handler: dist/index.processImage
    description: Image processing service
    events:
      - http:
          path: '{proxy+}'
          method: get
