service: nanny
frameworkVersion: '3'

plugins:
  - serverless-api-cloudfront

params:
  default:
    domain: ${sls:stage}.images.sjofartstidningen.se
  production:
    domain: images.sjofartstidningen.se

custom:
  apiCloudFront:
    domain: ${param:domain}
    certificate: ${env:AWS_CERTIFICATE_ARN}
    compress: true
    cookies: 'none'
    headers:
      - 'Accept'
    querystring: 'all'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${sls:stage}
  region: eu-north-1

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
          Resource: arn:aws:s3:::${env:S3_BUCKET_NAME}

  apiGateway:
    binaryMediaTypes:
      - '*/*'
      - 'image/*'
      - 'image/apng'
      - 'image/gif'
      - 'image/jpeg'
      - 'image/png'
      - 'image/svg+xml'
      - 'image/webp'

package:
  patterns:
    - '!node_modules/**'
    - '!.husky/**'
    - '!patches/**'
    - '!src/**'
    - 'dist/**'

functions:
  processImage:
    environment:
      NODE_ENV: ${self:provider.stage}
      S3_BUCKET: ${env:S3_BUCKET_NAME}
      FORCE_WEBP: true
    handler: dist/index.processImage
    description: Image processing service
    events:
      - http:
          path: '{proxy+}'
          method: get
