service: nanny

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-api-cloudfront

custom: ${file(./serverless.config.js)}

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: ${env:S3_BUCKET_ARN}

package:
  exclude:
    - '**/*'
  include:
    - dist/**

functions:
  processImage:
    environment:
      NODE_ENV: ${self:provider.stage}
      S3_BUCKET: ${env:S3_BUCKET_NAME}
      FORCE_WEBP: true
    handler: dist/index.processImage
    description: Image processing service
    events:
      - http:
          path: '{proxy+}'
          method: get
          contentHandling: CONVERT_TO_BINARY
